version: '3'

services:
    csv_db:
        container_name: csv_db
        image: mysql:8
        command: --init-file /data/application/init.sql
        restart: always
        ports:
            - ${DB_PORT}:3306
        volumes:
            - csv-test:/var/lib/mysql
            - ./docker/conf/mysql:/etc/mysql
            - ./docker/init.sql:/data/application/init.sql
            - ./docker/supervisor:/etc/supervisor
        environment:
            MYSQL_ROOT_PASSWORD: W7zXgR0LHp4nV86T
            MYSQL_DATABASE: csv_test
            MYSQL_USER: maks
            MYSQL_PASSWORD: BGmUd3iPvDf6925
        logging:
            options:
                max-size: 10m

    apache-csv:
        build:
            context: ./
            dockerfile: docker/Dockerfile
        container_name: apache-csv
        volumes:
            - .:/var/www/html
            - ./docker/php/php.ini:/usr/local/etc/php/php.ini
        environment:
            PHP_IDE_CONFIG: "serverName=csv-docker"
            DB_PORT: 3306
            DB_HOST: csv_db

        restart: always
        ports:
            - ${APP_PORT}:80
        expose:
            - 9000
        depends_on:
            - csv_db


volumes:
    csv-test:
